AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lambda function to login and sign CloudFront cookies

Parameters:
  websiteDomain:
    Description: "Website domain"
    Type: "String"
  sessionDuration:
    Description: "Number of seconds the user has access to the file"
    Type: "Number"
  redirectOnSuccess:
    Description: "Whether to send a HTTP 200 or 302 on successful login (boolean)"
    Type: "String"
  cloudFrontKeypairId:
    Description: "CloudFront keypair ID"
    Type: "String"
    Default: ""
    NoEcho: true
  cloudFrontPrivateKey:
    Description: "Unencrypted CloudFront private key"
    Type: "String"
    NoEcho: true
  htpasswd:
    Description: "Unencrypted htpasswd file contents"
    Type: "String"
    NoEcho: true

Resources:

  #
  # Lambda function definition
  #
  LoginFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs4.3
      CodeUri: dist/lambda.zip
      Role: !GetAtt LambdaRole.Arn
      Environment:
        Variables:
          WEBSITE_DOMAIN: !Ref websiteDomain
          SESSION_DURATION: !Ref sessionDuration
          REDIRECT_ON_SUCCESS: !Ref redirectOnSuccess
          CLOUDFRONT_KEYPAIR_ID: !Ref cloudFrontKeypairId
          CLOUDFRONT_PRIVATE_KEY: !Ref cloudFrontPrivateKey
          HTPASSWD: !Ref htpasswd
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /login
            Method: post
